name: 'Deploy: SLPK-Server' 

on:
  push:
    branches:
      - main

jobs:
      push-image:
        runs-on: self-hosted
        steps:
          - name: 'Checkout'
            uses: actions/checkout@main
            with:
              submodules: recursive

          - name: 'Login GHCR'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{ secrets.TOKEN }}

          - name: 'Build Image'
            run: |
              docker build -t ghcr.io/extended-reality-lab/geovis-slpk-server .
              docker push ghcr.io/extended-reality-lab/geovis--slpk-server
